---
dist: trusty
sudo: required
language: ruby
rvm: 1.9.3
cache: bundler
service:
  - docker
bundler_args: --without system_tests
matrix:
  fast_finish: true
  include:
  - env: DISTRO=ubuntu-xenial
  - env: DISTRO=debian-jessie
stages:
  - build
  - cook
jobs:
  include:
    - stage: cook
      script: "bundle exec rake test:cook distro=$DISTRO"
    - stage: build
      script: "bundle exec rake test:build distro=$DISTRO"
