---
dist: trusty
sudo: required
language: ruby
rvm: 1.9.3
cache: bundler
service:
  - docker
bundler_args: --without system_tests
matrix:
  fast_finish: true
  include:
  - env: DISTRO=ubuntu-xenial
  - env: DISTRO=debian-jessie
script: "bundle exec rake test distro=$DISTRO"
