---
dist: trusty
sudo: required
language: ruby
cache: bundler
service:
  - docker
bundler_args: --without system_tests
script: "bundle exec rake test"
matrix:
  fast_finish: true
  include:
  - rvm: 1.9.3
